openapi: "3.0.0"
info:
  version: 1.0.0
  title: Accounts
  license:
    name: MIT
servers:
  - url: http://accounts.swagger.io/v1/accounts
paths:
  /v1/accounts:
    get:
      summary: List all accounts
      operationId: listAccounts
      tags:
        - accounts
      responses:
        '200':
          description: An array of accounts
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Accounts"
    post:
      summary: Create an account
      operationId: createAccount
      tags:
        - accounts
      responses:
        '201':
          description: Created account
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
components:
  schemas:
    Account:
      required:
        - account_name
        - account_nickname
        - account_owner_name
        - account_type
        - currency
      properties:
        account_name:
          type: string
        account_nickname:
          type: string
        account_owner_name:
          type: string
        account_type:
          type: string
        currency:
          type: string
        available_balance:
          type: string
        booked_balance:
          type: string
        status:
          type: string
    Accounts:
      type: array
      items:
        $ref: "#/components/schemas/Account"

